# Test your FastAPI endpoints

GET http://127.0.0.1:8000/products
Accept: application/json

###
GET http://127.0.0.1:8000/products/{{pk}}
Accept: application/json

###

POST http://127.0.0.1:8000/products
Content-Type: application/json

{
  "name": "product",
  "price": 20,
  "quantity": 100
}
###
DELETE http://127.0.0.1:8000/products/{{pk}}

###
